# Generated by Django 4.2.4 on 2023-08-27 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
