# Generated by Django 4.2.4 on 2023-08-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='images/default.png', upload_to='profile_pictures'),
        ),
    ]
